version: '3'
services:
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      DB_USER: postgres
      DB_HOST: db
      DB_NAME: postgres
      DB_PASSWORD: postgres
      DB_PORT: 5432
